# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 19:34
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_key_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.PathAndRename(b'accounts_avatars'), verbose_name='\u0430\u0432\u0430\u0442\u0430\u0440'),
        ),
    ]
