# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='level',
            field=models.SmallIntegerField(choices=[(10, 'Beginner, Elementary'), (20, 'Pre-Intermediate'), (30, 'Intermediate'), (40, 'Upper-Intermediate'), (50, 'Advanced'), (60, 'Proficiency')], default=10, verbose_name='\u0443\u0440\u043e\u0432\u0435\u043d\u044c \u0437\u043d\u0430\u043d\u0438\u044f'),
        ),
    ]
