# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_accept_call',
            field=models.BooleanField(default=False, verbose_name='\u043f\u0440\u0438\u043d\u0438\u043c\u0430\u0442\u044c \u0432\u0445\u043e\u0434\u044f\u0449\u0438\u0435 \u0437\u0432\u043e\u043d\u043a\u0438'),
        ),
    ]
