# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_confirmationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_confirm',
            field=models.BooleanField(default=False, verbose_name='email \u043f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d'),
        ),
    ]
