# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_is_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_dialog_active',
            field=models.BooleanField(default=False, verbose_name='\u0432 \u043f\u0440\u043e\u0446\u0435\u0441\u0441\u0435 \u0434\u0438\u0430\u043b\u043e\u0433\u0430'),
        ),
        migrations.AddField(
            model_name='account',
            name='last_dialog_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u0434\u0430\u0442\u0430 \u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u044f \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0435\u0433\u043e \u0434\u0438\u0430\u043b\u043e\u0433\u0430'),
        ),
        migrations.AddField(
            model_name='account',
            name='last_dialog_started',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u0434\u0430\u0442\u0430 \u0441\u0442\u0430\u0440\u0442\u0430 \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0435\u0433\u043e \u0434\u0438\u0430\u043b\u043e\u0433\u0430'),
        ),
    ]
