# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20171015_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='skypeid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0441\u043a\u0430\u0439\u043f id'),
        ),
    ]
