# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_skypeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='birth_year',
            field=models.SmallIntegerField(default=1970, verbose_name='\u0433\u043e\u0434 \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='sex',
            field=models.SmallIntegerField(choices=[(1, '\u041c\u0443\u0436\u0441\u043a\u043e\u0439'), (2, '\u0416\u0435\u043d\u0441\u043a\u0438\u0439')], default=1, verbose_name='\u043f\u043e\u043b'),
            preserve_default=False,
        ),
    ]
