# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangodashpanel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NaxsiConfig',
        ),
        migrations.DeleteModel(
            name='NaxsiData',
        ),
        migrations.DeleteModel(
            name='NaxsiMessage',
        ),
        migrations.DeleteModel(
            name='SecurityData',
        ),
        migrations.DeleteModel(
            name='SecurityLoginAttemptCorrect',
        ),
        migrations.DeleteModel(
            name='SecurityLoginAttemptIncorrect',
        ),
    ]
