# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 10:28
from __future__ import unicode_literals

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u0434\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='\u0434\u0430\u0442\u0430 \u0440\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f')),
                ('title', models.CharField(max_length=255, verbose_name='\u0438\u043c\u044f \u0434\u0438\u0430\u043b\u043e\u0433\u0430')),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0434\u0438\u0430\u043b\u043e\u0433\u0430')),
                ('title_image', models.ImageField(blank=True, null=True, upload_to=blog.models.PathAndRename('blog_title_images'))),
                ('is_published', models.BooleanField(default=False, verbose_name='\u0437\u0430\u043c\u0435\u0442\u043a\u0430 \u043e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', 'title'),
                'verbose_name': '\u0417\u0430\u043c\u0435\u0442\u043a\u0430',
                'verbose_name_plural': '\u0417\u0430\u043c\u0435\u0442\u043a\u0438',
            },
        ),
    ]
