# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='source_author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u0430\u0432\u0442\u043e\u0440'),
        ),
        migrations.AddField(
            model_name='blog',
            name='source_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='url \u0438\u0441\u0442\u043e\u0447\u043d\u0438\u043a\u0430'),
        ),
    ]
