# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 16:22
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171109_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.CharField(default=1, max_length=255, verbose_name='\u0441\u043b\u0430\u0433'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=255, verbose_name='\u0438\u043c\u044f \u0437\u0430\u043c\u0435\u0442\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title_image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.PathAndRename('blog_title_images'), verbose_name='\u0437\u0430\u0433\u043b\u0430\u0432\u043d\u0430\u044f \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0430'),
        ),
    ]
