# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171120_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(max_length=255, unique=True, verbose_name='\u0441\u043b\u0430\u0433'),
        ),
    ]
