# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 19:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveDialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u0434\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('running_at', models.DateTimeField(blank=True, null=True, verbose_name='\u0434\u0430\u0442\u0430 \u0437\u0430\u043f\u0443\u0441\u043a\u0430')),
            ],
            options={
                'ordering': ('created_at',),
                'verbose_name': '\u0414\u0438\u0430\u043b\u043e\u0433',
                'verbose_name_plural': '\u0414\u0438\u0430\u043b\u043e\u0433\u0438',
            },
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u0434\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='\u0434\u0430\u0442\u0430 \u0440\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f')),
                ('name', models.CharField(max_length=255, verbose_name='\u0438\u043c\u044f \u0434\u0438\u0430\u043b\u043e\u0433\u0430')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': '\u0414\u0438\u0430\u043b\u043e\u0433',
                'verbose_name_plural': '\u0414\u0438\u0430\u043b\u043e\u0433\u0438',
            },
        ),
        migrations.AddField(
            model_name='activedialog',
            name='dialog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogs.Dialog', verbose_name='\u0434\u0438\u0430\u043b\u043e\u0433'),
        ),
        migrations.AddField(
            model_name='activedialog',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master', to=settings.AUTH_USER_MODEL, verbose_name='\u0432\u0435\u0434\u0443\u0449\u0438\u0439'),
        ),
        migrations.AddField(
            model_name='activedialog',
            name='pupil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pupil', to=settings.AUTH_USER_MODEL, verbose_name='\u0432\u0435\u0434\u043e\u043c\u044b\u0439'),
        ),
        migrations.AlterUniqueTogether(
            name='activedialog',
            unique_together=set([('dialog', 'master')]),
        ),
    ]
