# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 13:55
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0004_auto_20170921_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activedialog',
            options={'ordering': ('created_at',), 'verbose_name': '\u0417\u0430\u043f\u0443\u0449\u0435\u043d\u043d\u044b\u0439 \u0434\u0438\u0430\u043b\u043e\u0433', 'verbose_name_plural': '\u0417\u0430\u043f\u0443\u0449\u0435\u043d\u043d\u044b\u0435 \u0434\u0438\u0430\u043b\u043e\u0433\u0438'},
        ),
        migrations.AddField(
            model_name='dialog',
            name='scenario',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='\u0441\u0446\u0435\u043d\u0430\u0440\u0438\u0439 \u0434\u0438\u0430\u043b\u043e\u0433\u0430'),
        ),
    ]
