# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 14:52
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0009_auto_20171005_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='activedialog',
            name='chat_messages',
            field=jsonfield.fields.JSONField(default=[], verbose_name='\u0447\u0430\u0442'),
        ),
    ]
