# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0010_activedialog_chat_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='\u0434\u0438\u0430\u043b\u043e\u0433 \u043e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d'),
        ),
    ]
