# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0012_auto_20171027_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activedialog',
            options={'ordering': ('-dialog__created_at',), 'verbose_name': '\u0417\u0430\u043f\u0443\u0449\u0435\u043d\u043d\u044b\u0439 \u0434\u0438\u0430\u043b\u043e\u0433', 'verbose_name_plural': '\u0417\u0430\u043f\u0443\u0449\u0435\u043d\u043d\u044b\u0435 \u0434\u0438\u0430\u043b\u043e\u0433\u0438'},
        ),
        migrations.AlterModelOptions(
            name='dialog',
            options={'ordering': ('-created_at', 'name'), 'verbose_name': '\u0414\u0438\u0430\u043b\u043e\u0433', 'verbose_name_plural': '\u0414\u0438\u0430\u043b\u043e\u0433\u0438'},
        ),
    ]
