# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels_presence', '0002_presence_max_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presence',
            name='max_age',
        ),
    ]
